[package]
name = "llvm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { features = ["llvm12-0"] }
logos = "0.12.0"