pub use anonymous_function::*;
pub use array::*;
pub use common::*;
pub use for_loop::*;
pub use function_parser::*;
pub use if_statement::*;
pub use statement::*;
pub use structure::*;
pub use type_declarator::*;
pub use variable_parser::*;
pub use while_loop::*;

mod common;
mod function_parser;
mod variable_parser;
mod statement;
mod if_statement;
mod for_loop;
mod while_loop;
mod structure;
mod array;
mod type_declarator;
mod anonymous_function;